# Site settings
title: Practice Jekyll Site
tagline: Working with the jekyll ssg system
email: bobcobb@net.com
description: >
  Practice website using the Jekyll SSG engine and 
  will form the basis for a portfolio projects website
baseurl: ""
url: "http://mysite.com"
exclude: ['README.md', 'Gemfile.lock', 'Gemfile']

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compact